 CREATE TABLE kdz_42_staging.flights (
 year int NOT NULL,
 quarter int NULL,
 month int NOT NULL,
 flight_date varchar(30) NOT NULL,
 reporting_airline varchar(10) NULL,
 tail_number varchar(10) NULL,
 flight_number varchar(15) NOT NULL,
 origin varchar(10) NULL,
 dest varchar(10) NULL,
 crs_dep_time time not NULL,
 dep_time time NULL,
 dep_delay_minutes float NULL,
 cancelled float NOT NULL,
 cancellation_code char(1) NULL,
 air_time float NULL,
 distance float NULL,
 weather_delay float NULL,
 loaded_ts timestamp default(now()),
 CONSTRAINT flights_pkey PRIMARY KEY (flight_date, flight_number, origin, dest, crs_dep_time));
 CREATE TABLE kdz_42_staging.weather (
 icao_code varchar(10) NOT NULL,
 local_datetime varchar(25) NOT NULL,
 t_air_temperature numeric(3, 1) NULL,
 p0_sea_lvl numeric(4, 1) NULL,
 p_station_lvl numeric(4, 1) NULL,
 u_humidity int4 NULL,
 dd_wind_direction varchar(100) NULL,
 ff_wind_speed int4 NULL,
 ff10_max_gust_value int4 NULL,
 ww_present varchar(100) NULL,
 ww_recent varchar(50) NULL,
 c_total_clouds varchar(200) NULL,
 vv_horizontal_visibility numeric(3, 1) NULL,
 td_temperature_dewpoint numeric(3, 1) NULL,
 loaded_ts timestamp NOT NULL DEFAULT now(),
 PRIMARY KEY (icao_code, local_datetime));
